default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
cache: &cache
  <<: *default
  migrations_paths: db/cache_migrate
queue: &queue
  <<: *default
  migrations_paths: db/queue_migrate

development:
  primary:
    <<: *default
    database: llm_q_development
  # cache:
  #   <<: *cache
  #   database: llm_q_cache
  queue:
    <<: *queue
    database: llm_q_queue
  # cable:
  #   <<: *default
  #   database: llm_q_cable
  #   migrations_paths: db/cable_migrate
test:
  <<: *default
  database: llm_q_test
production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  queue:
    <<: *primary_production
    url: <%= ENV['QUEUE_DATABASE_URL'] %>
    migrations_paths: db/queue_migrate
  cache:
    <<: *primary_production
    url: <%= ENV['CACHE_DATABASE_URL'] %>
